services:
  uomi-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uomi-node-ai-container
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    environment:
      # Uncomment and configure to enable monitoring
      # - MONITORING_WEBSOCKET_URL=ws://your-monitoring-server:8080/monitoring
      # - MONITORING_INTERVAL_SECONDS=10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0', '1']
    command: python uomi-ai.py